#ifndef HG_CODEERREUR_H
#define HG_CODEERREUR_H


typedef enum {ERR_OUVERTURE_FICHIER=-10, ERR_ALLOCATION /*-9*/, ERR_OUT_OF_RANGE /*-8*/, ERR_NOT_FOUND/*-7*/, ERR_OPERATION_INVALIDE/*-6*/, ERR_EXISTE_DEJA/*-5*/, ERR_NO_ERR = 0} CodeErreur;


#endif //HG_CODEERREUR_H
