#ifndef _CODEERREUR_H_
#define _CODEERREUR_H_


typedef enum {ERR_OUVERTURE_FICHIER=-10, ERR_ALLOCATION /*-9*/, ERR_OUT_OF_RANGE /*-8*/, ERR_NOT_FOUND/*-7*/, ERR_OPERATION_INVALIDE/*-6*/, ERR_EXISTE_DEJA/*-5*/, ERR_NO_ERR = 0} CodeErreur;


#endif //_CODEERREUR_H_
