#ifndef __CODEERREUR_H__
#define __CODEERREUR_H__

typedef enum {ERR_OUVERTURE_FICHIER=-10, ERR_ALLOCATION, ERR_OUT_OF_RANGE, ERR_NOT_FOUND, ERR_OPERATION_INVALIDE} CodeErreur;


#endif //__CODEERREUR_H__
